name: test
env:
  ECONNECT_DATABASE_HOST: ${{ secrets.ECONNECT_DATABASE_HOST }}
  ECONNECT_DATABASE_NAME: ${{ secrets.ECONNECT_DATABASE_NAME }}
  ECONNECT_DATABASE_PASSWORD: ${{ secrets.ECONNECT_DATABASE_PASSWORD }}
  ECONNECT_DATABASE_USER: ${{ secrets.ECONNECT_DATABASE_USER }}
  ECONNECT_GENE_TOKEN: ${{ secrets.ECONNECT_GENE_TOKEN }}
  
on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "requirements.txt"
          pip install sodapy
      - name: Test with pytest
        run: python -m pytest -v